// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"
#include "helpers.h"

napi_value dl_AU3_ClipGet(napi_env env, napi_callback_info cbinfo) {
  DL_PARAMS(1);
  DL_ALLOC_INT_PARAM(clipSize, 0);
  DL_OUTPUT_WSTR(AU3_ClipGet(clip, clipSize), clip);
  DL_FREE_INT_PARAM(clipSize);
  DL_RETURN;
}