// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"
#include "helpers.h"

napi_value dl_AU3_MouseClick(napi_env env, napi_callback_info cbinfo) {
  DL_PARAMS(5);
  DL_ALLOC_INWSTR_PARAM(button, 0);
  DL_ALLOC_INT_PARAM(x, 1);
  DL_ALLOC_INT_PARAM(y, 2);
  DL_ALLOC_INT_PARAM(clickCount, 3);
  DL_ALLOC_INT_PARAM(speed, 4);
  DL_OUTPUT_INT_STATUS(AU3_MouseClick(button, x, y, clickCount, speed),
                       AU3_MouseClick);
  DL_FREE_INT_PARAM(speed);
  DL_FREE_INT_PARAM(clickCount);
  DL_FREE_INT_PARAM(y);
  DL_FREE_INT_PARAM(x);
  DL_FREE_INWSTR_PARAM(button);
  DL_RETURN;
}