// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"

#include "helpers.h"

napi_value dl_AU3_MouseClickDrag(napi_env env, napi_callback_info cbinfo) {
  DL_PARAMS(6);
  DL_ALLOC_INWSTR_PARAM(button, 0);
  DL_ALLOC_INT_PARAM(xStart, 1);
  DL_ALLOC_INT_PARAM(yStart, 2);
  DL_ALLOC_INT_PARAM(xEnd, 3);
  DL_ALLOC_INT_PARAM(yEnd, 4);
  DL_ALLOC_INT_PARAM(speed, 5);
  DL_OUTPUT_INT_STATUS(
      AU3_MouseClickDrag(button, xStart, yStart, xEnd, yEnd, speed),
      AU3_MouseClickDrag);
  DL_FREE_INT_PARAM(speed);
  DL_FREE_INT_PARAM(yEnd);
  DL_FREE_INT_PARAM(xEnd);
  DL_FREE_INT_PARAM(yStart);
  DL_FREE_INT_PARAM(xStart);
  DL_FREE_INWSTR_PARAM(button);
  DL_RETURN;
}