// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"
#include "helpers.h"

napi_value dl_AU3_WinMenuSelectItemByHandle(napi_env env,
                                            napi_callback_info cbinfo) {
  DL_PARAMS(9);
  DL_ALLOC_INT_PARAM(window, 0);
  DL_ALLOC_INWSTR_PARAM(item0, 1);
  DL_ALLOC_INWSTR_PARAM(item1, 2);
  DL_ALLOC_INWSTR_PARAM(item2, 3);
  DL_ALLOC_INWSTR_PARAM(item3, 4);
  DL_ALLOC_INWSTR_PARAM(item4, 5);
  DL_ALLOC_INWSTR_PARAM(item5, 6);
  DL_ALLOC_INWSTR_PARAM(item6, 7);
  DL_ALLOC_INWSTR_PARAM(item7, 8);
  DL_OUTPUT_INT_STATUS(AU3_WinMenuSelectItemByHandle(window, item0, item1,
                                                     item2, item3, item4, item5,
                                                     item6, item7),
                       AU3_WinMenuSelectItemByHandle);
  DL_FREE_INWSTR_PARAM(item7);
  DL_FREE_INWSTR_PARAM(item6);
  DL_FREE_INWSTR_PARAM(item5);
  DL_FREE_INWSTR_PARAM(item4);
  DL_FREE_INWSTR_PARAM(item3);
  DL_FREE_INWSTR_PARAM(item2);
  DL_FREE_INWSTR_PARAM(item1);
  DL_FREE_INWSTR_PARAM(item0);
  DL_FREE_INT_PARAM(window);
  DL_RETURN;
}