// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"

#include "helpers.h"

napi_value dl_AU3_WinMoveByHandle(napi_env env, napi_callback_info cbinfo) {
  DL_PARAMS(5);
  DL_ALLOC_HWND_PARAM(window, 0);
  DL_ALLOC_INT_PARAM(x, 1);
  DL_ALLOC_INT_PARAM(y, 2);
  DL_ALLOC_INT_PARAM(width, 3);
  DL_ALLOC_INT_PARAM(height, 4);
  DL_OUTPUT_INT_STATUS(AU3_WinMoveByHandle(window, x, y, width, height),
                       AU3_WinMoveByHandle);
  DL_FREE_INT_PARAM(height);
  DL_FREE_INT_PARAM(width);
  DL_FREE_INT_PARAM(y);
  DL_FREE_INT_PARAM(x);
  DL_FREE_HWND_PARAM(window);
  DL_RETURN;
}