// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"
#include "helpers.h"

napi_value dl_AU3_WinMenuSelectItem(napi_env env, napi_callback_info cbinfo) {
  DL_PARAMS(10);
  DL_ALLOC_INWSTR_PARAM(windowDescription, 0);
  DL_ALLOC_INWSTR_PARAM(windowText, 1);
  DL_ALLOC_INWSTR_PARAM(item0, 2);
  DL_ALLOC_INWSTR_PARAM(item1, 3);
  DL_ALLOC_INWSTR_PARAM(item2, 4);
  DL_ALLOC_INWSTR_PARAM(item3, 5);
  DL_ALLOC_INWSTR_PARAM(item4, 6);
  DL_ALLOC_INWSTR_PARAM(item5, 7);
  DL_ALLOC_INWSTR_PARAM(item6, 8);
  DL_ALLOC_INWSTR_PARAM(item7, 9);
  DL_OUTPUT_INT_STATUS(AU3_WinMenuSelectItem(windowDescription, windowText,
                                             item0, item1, item2, item3, item4,
                                             item5, item6, item7),
                       AU3_WinMenuSelectItem);
  DL_FREE_INWSTR_PARAM(item7);
  DL_FREE_INWSTR_PARAM(item6);
  DL_FREE_INWSTR_PARAM(item5);
  DL_FREE_INWSTR_PARAM(item4);
  DL_FREE_INWSTR_PARAM(item3);
  DL_FREE_INWSTR_PARAM(item2);
  DL_FREE_INWSTR_PARAM(item1);
  DL_FREE_INWSTR_PARAM(item0);
  DL_FREE_INWSTR_PARAM(windowText);
  DL_FREE_INWSTR_PARAM(windowDescription);
  DL_RETURN;
}