// This file is generated by src/codegen/function-gen.ts.
#include <node_api.h>

#include "AutoItX3_DLL.h"

#include "helpers.h"

napi_value dl_AU3_WinSetStateByHandle(napi_env env, napi_callback_info cbinfo) {
  DL_PARAMS(2);
  DL_ALLOC_HWND_PARAM(window, 0);
  DL_ALLOC_INT_PARAM(state, 1);
  DL_OUTPUT_INT_STATUS(AU3_WinSetStateByHandle(window, state),
                       AU3_WinSetStateByHandle);
  DL_FREE_INT_PARAM(state);
  DL_FREE_HWND_PARAM(window);
  DL_RETURN;
}