export { autoitSetOptions } from './autoitSetOptions'

// Generated functions

export { init } from './generated/init'
export { error } from './generated/error'
// export { autoitSetOption } from './generated/autoitSetOption'
export { clipGet } from './generated/clipGet'
export { clipPut } from './generated/clipPut'
export { controlClick } from './generated/controlClick'
export { controlClickByHandle } from './generated/controlClickByHandle'
// export { controlCommand } from './generated/controlCommand'
// export { controlCommandByHandle } from './generated/controlCommandByHandle'
// export { controlListView } from './generated/controlListView'
// export { controlListViewByHandle } from './generated/controlListViewByHandle'
export { controlDisable } from './generated/controlDisable'
export { controlDisableByHandle } from './generated/controlDisableByHandle'
export { controlEnable } from './generated/controlEnable'
export { controlEnableByHandle } from './generated/controlEnableByHandle'
export { controlFocus } from './generated/controlFocus'
export { controlFocusByHandle } from './generated/controlFocusByHandle'
export { controlGetFocus } from './generated/controlGetFocus'
export { controlGetFocusByHandle } from './generated/controlGetFocusByHandle'
export { controlGetHandle } from './generated/controlGetHandle'
// export { controlGetHandleAsText } from './generated/controlGetHandleAsText'
// export { controlGetPos } from './generated/controlGetPos'
// export { controlGetPosByHandle } from './generated/controlGetPosByHandle'
export { controlGetText } from './generated/controlGetText'
export { controlGetTextByHandle } from './generated/controlGetTextByHandle'
export { controlHide } from './generated/controlHide'
export { controlHideByHandle } from './generated/controlHideByHandle'
export { controlMove } from './generated/controlMove'
export { controlMoveByHandle } from './generated/controlMoveByHandle'
export { controlSend } from './generated/controlSend'
export { controlSendByHandle } from './generated/controlSendByHandle'
export { controlSetText } from './generated/controlSetText'
export { controlSetTextByHandle } from './generated/controlSetTextByHandle'
export { controlShow } from './generated/controlShow'
export { controlShowByHandle } from './generated/controlShowByHandle'
// export { controlTreeView } from './generated/controlTreeView'
// export { controlTreeViewByHandle } from './generated/controlTreeViewByHandle'
// export { driveMapAdd } from './generated/driveMapAdd'
// export { driveMapDel } from './generated/driveMapDel'
// export { driveMapGet } from './generated/driveMapGet'
export { isAdmin } from './generated/isAdmin'
export { mouseClick } from './generated/mouseClick'
export { mouseClickDrag } from './generated/mouseClickDrag'
export { mouseDown } from './generated/mouseDown'
export { mouseGetCursor } from './generated/mouseGetCursor'
// export { mouseGetPos } from './generated/mouseGetPos'
// export { mouseMove } from './generated/mouseMove'
// export { mouseUp } from './generated/mouseUp'
// export { mouseWheel } from './generated/mouseWheel'
// export { opt } from './generated/opt'
// export { pixelChecksum } from './generated/pixelChecksum'
// export { pixelGetColor } from './generated/pixelGetColor'
// export { pixelSearch } from './generated/pixelSearch'
// export { processClose } from './generated/processClose'
// export { processExists } from './generated/processExists'
// export { processSetPriority } from './generated/processSetPriority'
// export { processWait } from './generated/processWait'
// export { processWaitClose } from './generated/processWaitClose'
// export { run } from './generated/run'
// export { runWait } from './generated/runWait'
// export { runAs } from './generated/runAs'
// export { runAsWait } from './generated/runAsWait'
// export { send } from './generated/send'
// export { shutdown } from './generated/shutdown'
// export { sleep } from './generated/sleep'
// export { statusbarGetText } from './generated/statusbarGetText'
// export { statusbarGetTextByHandle } from './generated/statusbarGetTextByHandle'
// export { toolTip } from './generated/toolTip'
export { winActivate } from './generated/winActivate'
export { winActivateByHandle } from './generated/winActivateByHandle'
export { winActive } from './generated/winActive'
export { winActiveByHandle } from './generated/winActiveByHandle'
export { winClose } from './generated/winClose'
export { winCloseByHandle } from './generated/winCloseByHandle'
// export { winExists } from './generated/winExists'
// export { winExistsByHandle } from './generated/winExistsByHandle'
// export { winGetCaretPos } from './generated/winGetCaretPos'
// export { winGetClassList } from './generated/winGetClassList'
// export { winGetClassListByHandle } from './generated/winGetClassListByHandle'
// export { winGetClientSize } from './generated/winGetClientSize'
// export { winGetClientSizeByHandle } from './generated/winGetClientSizeByHandle'
export { winGetHandle } from './generated/winGetHandle'
// export { winGetHandleAsText } from './generated/winGetHandleAsText'
// export { winGetPos } from './generated/winGetPos'
// export { winGetPosByHandle } from './generated/winGetPosByHandle'
// export { winGetProcess } from './generated/winGetProcess'
// export { winGetProcessByHandle } from './generated/winGetProcessByHandle'
// export { winGetState } from './generated/winGetState'
// export { winGetStateByHandle } from './generated/winGetStateByHandle'
// export { winGetText } from './generated/winGetText'
// export { winGetTextByHandle } from './generated/winGetTextByHandle'
export { winGetTitle } from './generated/winGetTitle'
// export { winGetTitleByHandle } from './generated/winGetTitleByHandle'
// export { winKill } from './generated/winKill'
// export { winKillByHandle } from './generated/winKillByHandle'
// export { winMenuSelectItem } from './generated/winMenuSelectItem'
// export { winMenuSelectItemByHandle } from './generated/winMenuSelectItemByHandle'
// export { winMinimizeAll } from './generated/winMinimizeAll'
// export { winMinimizeAllUndo } from './generated/winMinimizeAllUndo'
// export { winMove } from './generated/winMove'
// export { winMoveByHandle } from './generated/winMoveByHandle'
// export { winSetOnTop } from './generated/winSetOnTop'
// export { winSetOnTopByHandle } from './generated/winSetOnTopByHandle'
// export { winSetState } from './generated/winSetState'
// export { winSetStateByHandle } from './generated/winSetStateByHandle'
// export { winSetTitle } from './generated/winSetTitle'
// export { winSetTitleByHandle } from './generated/winSetTitleByHandle'
// export { winSetTrans } from './generated/winSetTrans'
// export { winSetTransByHandle } from './generated/winSetTransByHandle'
// export { winWait } from './generated/winWait'
// export { winWaitByHandle } from './generated/winWaitByHandle'
// export { winWaitActive } from './generated/winWaitActive'
// export { winWaitActiveByHandle } from './generated/winWaitActiveByHandle'
// export { winWaitClose } from './generated/winWaitClose'
// export { winWaitCloseByHandle } from './generated/winWaitCloseByHandle'
// export { winWaitNotActive } from './generated/winWaitNotActive'
// export { winWaitNotActiveByHandle } from './generated/winWaitNotActiveByHandle'
